# Generated by Django 4.0.6 on 2022-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('NDI', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Horas_t', models.PositiveSmallIntegerField()),
                ('Horas_p', models.PositiveSmallIntegerField()),
                ('Creditos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
